project:
  type: website
  output-dir: docs

website:
  title: "Alejandro Duque - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: labs/lab_0/lab0_duque.qmd
            text: "Lab 0: dplyr Basics"
          - href: labs/lab_1/lab1_duque.qmd
            text: "Lab 1: Census Data Quality for Policy Decisions"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
